##
# CAS Server Context Configuration
#
server:
  context-path: /cas
  port: 8443
  ssl:
    key-store: classpath:jbonekeystore
    key-store-password: 123456
    key-password: 123456
    enabled: true
  tomcat:
    max-http-post-size: 2097152
    basedir: build/tomcat
    max-threads: 10
    port-header: X-Forwarded-Port
    protocol-header: X-Forwarded-Proto
    protocol-header-https-value: https
    remote-ip-header: X-FORWARDED-FOR
    uri-encoding: UTF-8

cas:
  authn:
    shiro:
      requiredRoles: sso
      location: classpath:shiro.ini
    pm:
      enabled: true
      #policyPattern: ^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d){8,10}
      reset:
        text: 请使用以下链接重置您的密码： %s
        subject: Jbone重置密码邮件
        from: jbone666@163.com
        expirationMinutes: 10
        emailAttribute: mail
        securityQuestionsEnabled: true
        autoLogin: false
    pac4j:
      #github三方账号授权登录，可自行修改成自己的id和secret
      github:
        id: 151e91b5b0018290a074
        secret: 3db661368363a8775d7b6bf7603710e6d90f490e
        profileAttrs.id: id
        client-name: github
  server:
    name: https://jbone-cas.majunwei.com:8443
    prefix: https://jbone-cas.majunwei.com:8443/cas
  adminPagesSecurity:
    #CAS监控授权的IP,测试时127.0.0.1是必须的，第一个配置本机IP。如果是生产环境只需要配置jbone-sm-admin的IP即可
    ip: (172\.16\.180\.163)|(127\.0\.0\.1)
    actuatorEndpointsEnabled: true
  monitor:
    endpoints:
      dashboard:
        enabled: true
        sensitive: true
  #使用json加载注册到CAS上的服务，还可以使用redis／rest等方式
  serviceRegistry:
    initFromJson: false
    jpa:
      healthQuery: select now()
      isolateInternalQueries: false
      url: jdbc:mysql://121.42.174.77:3306/jbone_cas?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
      failFastTimeout: 1
      dialect: org.hibernate.dialect.MySQL5Dialect
      leakThreshold: 10
      jpaLockingTgtEnabled: true
      batchSize: 1
      user: jbone_cas
      ddlAuto: none
      password: Jbone_cas_666
      autocommit: false
      driverClass: com.mysql.jdbc.Driver
      idleTimeout: 5000
      dataSourceName:
      dataSourceProxy: false
      properties.hibernate.hbm2ddl.auto: none
      properties.hibernate.show_sql: true
      pool.suspension: false
      pool.minSize: 6
      pool.maxSize: 18
      pool.maxWait: 2000

  #票据持久化，用于分布式管理用户票据
  ticket:
    registry:
      jpa:
        ticketLockType: NONE
        jpaLockingTimeout: 3600
        healthQuery: select now()
        isolateInternalQueries: false
        url: jdbc:mysql://121.42.174.77:3306/jbone_cas?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
        failFastTimeout: 1
        dialect: org.hibernate.dialect.MySQL5Dialect
        leakThreshold: 10
        jpaLockingTgtEnabled: true
        batchSize: 1
        defaultCatalog:
        defaultSchema: jbone_cas
        user: jbone_cas
        ddlAuto: none
        password: Jbone_cas_666
        autocommit: false
        driverClass: com.mysql.jdbc.Driver
        idleTimeout: 5000
        dataSourceName:
        dataSourceProxy: false

        # Hibernate-specific properties (i.e. `hibernate.globally_quoted_identifiers`)
        properties.hibernate.hbm2ddl.auto: none
        properties.hibernate.show_sql: true

        pool.suspension: false
        pool.minSize: 6
        pool.maxSize: 18
        pool.maxWait: 2000

        crypto.signing.key:
        crypto.signing.keySize: 512
        crypto.encryption.key:
        crypto.encryption.keySize: 16
        crypto.alg: AES
        crypto.enabled: false
    tgt:
      # 启用rememberMe
      rememberMe:
        enabled: true
        timeToKillInSeconds: 28800
      # tgt有效期（会话超时时间）
      timeout:
        maxTimeToLiveInSeconds: 28800
    st:
      maxLength: 20
      # ST使用次数
      numberOfUses: 1
      # ST有效期600S
      timeToKillInSeconds: 600
  #单点登出
  slo:
    disabled: false
    asynchronous: true
  #验证码,申请地址：https://www.google.com/recaptcha/admin (默认关闭，登录太麻烦)
#  googleRecaptcha:
#    verifyUrl: https://www.google.com/recaptcha/api/siteverify
#    siteKey: 6666LcsZ2oUAAAAAMCxIHtsEcWnyUp4NVHEaatCrwUK
#    secret: 6666LcsZ2oUAAAAAFjw1U8OGVo8R-F3az_FM7uc-m88
spring:
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force  : true
  cloud:
    bus:
      enabled: false
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML
  aop:
    auto: true
    proxy-target-class: true
  application:
    name: Jbone-CAS
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  sleuth:
    sampler:
      percentage: 1
  mail:
    host: smtp.163.com
    ##port: 25
    username: jbone666@163.com
    password: jbonesq2018
    testConnection: true
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

#取消management安全验证
management.security.enabled: false
#单独配置management的context-path
management.context-path: /status
management.add-application-context-header: false
#单独配置监控端口
management.port: 30003
#禁用management的ssl
management.ssl.enabled: false



# 开启endpoints start #
endpoints.enabled: true
endpoints.sensitive: false

endpoints.restart.enabled: true
endpoints.shutdown.enabled: false

cas.monitor.endpoints.dashboard.enabled: true
cas.monitor.endpoints.dashboard.sensitive: false

cas.monitor.endpoints.discovery.enabled: true
cas.monitor.endpoints.discovery.sensitive: false

cas.monitor.endpoints.auditEvents.enabled: true
cas.monitor.endpoints.auditEvents.sensitive: false

cas.monitor.endpoints.authenticationEvents.enabled: true
cas.monitor.endpoints.authenticationEvents.sensitive: false

cas.monitor.endpoints.configurationState.enabled: true
cas.monitor.endpoints.configurationState.sensitive: false

cas.monitor.endpoints.healthCheck.enabled: true
cas.monitor.endpoints.healthCheck.sensitive: false

cas.monitor.endpoints.loggingConfig.enabled: true
cas.monitor.endpoints.loggingConfig.sensitive: false

cas.monitor.endpoints.metrics.enabled: true
cas.monitor.endpoints.metrics.sensitive: false

cas.monitor.endpoints.attributeResolution.enabled: true
cas.monitor.endpoints.attributeResolution.sensitive: false

cas.monitor.endpoints.singleSignOnReport.enabled: true
cas.monitor.endpoints.singleSignOnReport.sensitive: false

cas.monitor.endpoints.statistics.enabled: true
cas.monitor.endpoints.statistics.sensitive: false

cas.monitor.endpoints.trustedDevices.enabled: true
cas.monitor.endpoints.trustedDevices.sensitive: false

cas.monitor.endpoints.status.enabled: true
cas.monitor.endpoints.status.sensitive: false

cas.monitor.endpoints.singleSignOnStatus.enabled: true
cas.monitor.endpoints.singleSignOnStatus.sensitive: false

cas.monitor.endpoints.springWebflowReport.enabled: true
cas.monitor.endpoints.springWebflowReport.sensitive: false

cas.monitor.endpoints.registeredServicesReport.enabled: true
cas.monitor.endpoints.registeredServicesReport.sensitive: false

cas.monitor.endpoints.configurationMetadata.enabled: true
cas.monitor.endpoints.configurationMetadata.sensitive: false

# 开启endpoints end #


logging:
  config: classpath:log4j2.xml

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:10001/eureka/
    metadata-map:
      user.name: jbone
      user.password: jbone
    healthcheck.enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#    statusPageUrl: http://${spring.cloud.client.ipAddress}:${management.port}/status/info
#    healthCheckUrl: http://${spring.cloud.client.ipAddress}:${management.port}/status/health
#    homePageUrl: http://${spring.cloud.client.ipAddress}:${management.port}/
#https的健康检测url
#    secureHealthCheckUrl: http://${spring.cloud.client.ipAddress}:${management.port}/status/health
#https端口
#    securePort: 8443
#启用https安全端口
#    securePortEnabled: true
#    nonSecurePortEnabled: false
#boot-admin在监控时，需要从metadata-map中获取context-path和port
    metadata-map:
      management.context-path: ${management.context-path}
      management.port: ${management.port}
ribbon:
    ConnectTimeout: 500
    ReadTimeout: 3000
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true

jbone.rpc.sysServer.feign:
  protocol: http
  name: jbone-sys-server

# info接口返回值
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  java:
    version: ${java.version}
  code:
    git: https://github.com/417511458/jbone
    gitee: https://gitee.com/majunwei2017/jbone
  domain: http://www.majunwei.com

# 不允许静态用户
staticAuthentication: false

# 启用超时设置
hystrix.command.default.execution.timeout.enabled: true
# 熔断时间为10S
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
# 使用线程隔离熔断
hystrix.command.default.execution.isolation.strategy: THREAD
# 核心线程数100
hystrix.threadpool.default.coreSize: 100
# 超时时熔断
hystrix.command.default.execution.isolation.thread.interruptOnTimeout: true
# 取消时是否熔断
hystrix.command.default.execution.isolation.thread.interruptOnCancel: false
