#服务
server:
  port: 50003

spring:
  application:
    name: jbone-cms-portal
  redis:
    host: 10.251.35.116
    port: 6379
    password: jboneonline
  #rabbitmq配置
  rabbitmq:
    host: 10.251.35.116
    port: 5672
    username: admin
    password: 123456
  thymeleaf:
    cache: false
    enabled: true
  freemarker:
    enabled: false
  jpa:
    show-sql: true

  #
  # 以下为 zipkin客户端配置
  #
  sleuth:
    sampler:
      probability: 1
    messaging:
      enabled: true
      rabbit:
        enabled: true
  zipkin:
    sender:
      type: rabbit

zipkin.rabbitmq.queue: zipkin

# ###


#注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://10.251.35.116:10001/eureka,http://10.163.185.74:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS

#Jbone配置
jbone:
  cas:
    #CAS服务地址
    casServerUrl: http://cas.jbone.cn
    #当前系统地址
    currentServerUrlPrefix: http://jbone.cn
    #过滤器地址,CAS认证通过后会回掉到jbone.cas.currentServerUrlPrefix/jbone.cas.casFilterUrlPattern
    casFilterUrlPattern: /cas
    #登录成功后的跳转路径，默认"/"
    successUrl: http://jbone.cn/
    #未授权的跳转路径，默认"/403"
    unauthorizedUrl: /403
    #客户端Session失效时间，默认30分钟
    clientSessionTimeout: 1800000
    #权限过滤规则
    filterChainDefinition:
      "[/actuator/**]": anon  #不过滤监控端口，此处巨坑，升级到2。0之后必须用[]括起来，否则会规律所有符号.
      "[/login]": authc
      "[/**]": anon
  #当前系统名，在系统管理里面对应的名字
  sys:
    serverName: jbone-cms-portal

# info接口返回值
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  java:
    version: ${java.version}
  code:
    git: https://github.com/417511458/jbone
    gitee: https://gitee.com/majunwei2017/jbone
  domain: http://www.majunwei.com

# 启用超时设置
hystrix.command.default.execution.timeout.enabled: true
# 熔断时间为10S
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
# 使用线程隔离熔断
hystrix.command.default.execution.isolation.strategy: THREAD
# 核心线程数100
hystrix.threadpool.default.coreSize: 100
# 超时时熔断
hystrix.command.default.execution.isolation.thread.interruptOnTimeout: true
# 取消时是否熔断
hystrix.command.default.execution.isolation.thread.interruptOnCancel: false