spring:
  application:
    name: jbone-sm-admin
  redis:
    host: 127.0.0.1
    port: 6379
    password: jbone
  cloud:
    config:
    enabled: false
  boot:
    admin:
      monitor:
        #监控超时时间
        connect-timeout: 30000
        default-retries: 2
     #probed-endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream
      # turbine监控配置
      # clusters是指监控的集群
      # location是turbine服务的ID，Jbone中使用jbone-sm-monitor作为turbine监控服务
      turbine:
        location: http://jbone-sm-monitor.majunwei.com:10003/
      context-path: /admin

server.port: 10002

#注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}


# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS


#SSO服务地址
jbone:
  sso:
    ssoServerUrl: http://sso.local.jbone.cn
    #当前系统地址
    currentServerUrlPrefix: http://smadmin.local.jbone.cn
    #过滤器地址,SSO认证通过后会回掉到jbone.sso.currentServerUrlPrefix/jbone.sso.ssoFilterUrlPattern
    ssoFilterUrlPattern: /sso
    #登录成功后的跳转路径，默认"/"
    successUrl: /admin/
    logoutUrl: /admin/logout
    #未授权的跳转路径，默认"/403"
    unauthorizedUrl: /403
    clientSessionTimeout: 1800000
    #权限过滤规则
    filterChainDefinition:
      "[/actuator/**]": anon  #不过滤监控端口，此处巨坑，升级到2。0之后必须用[]括起来，否则会规律所有符号.
      "[/admin/**]": authc,roles[serverAdministrator]
      "[/**]": anon
  #系统服务名称
  sys:
    serverName: jbone-sm-admin
    #feign通讯协议，默认http://
    serverProtoal: http://
  #系统管理Feign调用配置
  rpc.sysServer.feign:
    protocol: http
    name: jbone-sys-server

# info接口返回值
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  java:
    version: ${java.version}
  code:
    git: https://github.com/417511458/jbone
    gitee: https://gitee.com/majunwei2017/jbone
  domain: http://www.jbone.cn

# 启用超时设置
hystrix.command.default.execution.timeout.enabled: true
# 熔断时间为10S
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
# 使用线程隔离熔断
hystrix.command.default.execution.isolation.strategy: THREAD
# 核心线程数100
hystrix.threadpool.default.coreSize: 100
# 超时时熔断
hystrix.command.default.execution.isolation.thread.interruptOnTimeout: true
# 取消时是否熔断
hystrix.command.default.execution.isolation.thread.interruptOnCancel: false
