spring:
  application:
    name: jbone-b2b2c-item-server
  redis:
    host: 127.0.0.1
    port: 6379
    password: jbone
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  thymeleaf:
    cache: false
    enabled: true
  freemarker:
    enabled: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://121.42.174.77:3306/jbone_b2b2c_item?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: jbone_b2b2c_item
    password: Jbone_b2b2c_item_666
    driver-class-name: com.mysql.jdbc.Driver


#服务
server:
  port: 8011

#注册中心
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

management:
  security:
    enabled: false

#Jbone配置
jbone:
  #当前系统名，在系统管理里面对应的名字
  sys:
    serverName: jbone-b2b2c-item-server

# info接口返回值
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  java:
    version: ${java.version}
  code:
    git: https://github.com/417511458/jbone
    gitee: https://gitee.com/majunwei2017/jbone
  domain: http://www.majunwei.com

