spring:
  application:
    name: jbone-sm-zipkinserver
  redis:
    host: 127.0.0.1
    port: 6379
    password: jbone
  #rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  #禁用sleuth，改用rabbitmq
  sleuth:
    enabled: false


#
# zipkin配置
#

  # 调用链数据源配置
  datasource:
#    schema: classpath:/mysql.sql
    url: jdbc:mysql://121.42.174.77:3306/jbone_zipkin?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: jbone_zipkin
    password: Jbone_zipkin_666
    driver-class-name: com.mysql.jdbc.Driver
    continue-on-error: true
  zipkin:
    sender:
      type: rabbit
# 调用链配置mysql存储
zipkin:
  storage:
    type: mysql
    StorageComponent: mysql
  collector:
    rabbitmq:
      addresses: localhost:5672
      username: guest
      password: guest
      queue: zipkin

# 服务端口
server:
  port: 10004

# 注册中心配置
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10001/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

# 服务管理配置
management:
  endpoints:
    web:
      exposure:
        include: "*"        #暴漏的接口，"*"表示所有web监控接口
        exclude:            #不暴漏的接口
      base-path: /actuator  #监控根路径
  endpoint:
    health:
      show-details: ALWAYS
  metrics:
    web:
      server:
        auto-time-requests: false #解决zipkin异常：Prometheus requires that all meters with the same name have the same set of tag keys
jbone:
  #CAS服务地址
  cas:
    casServerUrl: http://jbone-cas.majunwei.com:30001/cas
    #当前系统地址
    currentServerUrlPrefix: http://jbone-sm-zipkinserver.majunwei.com:10004
    #过滤器地址,CAS认证通过后会回掉到jbone.cas.currentServerUrlPrefix/jbone.cas.casFilterUrlPattern
    casFilterUrlPattern: /cas
    #登录成功后的跳转路径，默认"/"
    successUrl: /zipkin/
    #未授权的跳转路径，默认"/403"
    unauthorizedUrl: /403
    #权限过滤规则
    filterChainDefinition:
      "[/actuator/**]": anon  #不过滤监控端口，此处巨坑，升级到2。0之后必须用[]括起来，否则会规律所有符号.
      "[/zipkin/**]": authc,roles[serverAdministrator]
      "[/**]": anon
      "[/login]": anon
    clientSessionTimeout: 180000 #客户端Session失效时间，默认30分钟
  #系统配置
  sys:
    serverName: jbone-sm-zipkinserver
    serverProtoal: http:// #feign通讯协议，默认http://
  #系统管理Feign调用配置
  rpc.sysServer.feign:
    protocol: http
    name: jbone-sys-server

# info接口返回值
info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
  java:
    version: ${java.version}
  code:
    git: https://github.com/417511458/jbone
    gitee: https://gitee.com/majunwei2017/jbone
  domain: http://www.majunwei.com

# 启用超时设置
hystrix.command.default.execution.timeout.enabled: true
# 熔断时间为10S
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
# 使用线程隔离熔断
hystrix.command.default.execution.isolation.strategy: THREAD
# 核心线程数100
hystrix.threadpool.default.coreSize: 100
# 超时时熔断
hystrix.command.default.execution.isolation.thread.interruptOnTimeout: true
# 取消时是否熔断
hystrix.command.default.execution.isolation.thread.interruptOnCancel: false
